# Generated by Django 4.1.4 on 2023-03-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contproc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(max_length=1000)),
            ],
        ),
    ]
